package constants

const THREATCODE_EXIT_CODE_OK = 0
const THREATCODE_EXIT_CODE_ERROR = 2
const THREATCODE_INTEGRATION_NAME = "CLI_V1_PLUGIN"
const THREATCODE_INTEGRATION_NAME_ENV = "THREATCODE_INTEGRATION_NAME"
const THREATCODE_INTEGRATION_VERSION_ENV = "THREATCODE_INTEGRATION_VERSION"
const THREATCODE_HTTPS_PROXY_ENV = "HTTPS_PROXY"
const THREATCODE_HTTP_PROXY_ENV = "HTTP_PROXY"
const THREATCODE_HTTP_NO_PROXY_ENV = "NO_PROXY"
const THREATCODE_NPM_PROXY_ENV = "NPM_CONFIG_PROXY"
const THREATCODE_NPM_HTTPS_PROXY_ENV = "NPM_CONFIG_HTTPS_PROXY"
const THREATCODE_NPM_HTTP_PROXY_ENV = "NPM_CONFIG_HTTP_PROXY"
const THREATCODE_NPM_NO_PROXY_ENV = "NPM_CONFIG_NO_PROXY"
const THREATCODE_NPM_ALL_PROXY = "ALL_PROXY"
const THREATCODE_CA_CERTIFICATE_LOCATION_ENV = "NODE_EXTRA_CA_CERTS"
const THREATCODE_DEFAULT_API_URL = "https://api.threatcode.io"
const THREATCODE_INTERNAL_NO_PROXY = "localhost,127.0.0.1,::1"
const THREATCODE_OAUTH_ACCESS_TOKEN_ENV = "THREATCODE_OAUTH_TOKEN"

const THREATCODE_HTTPS_PROXY_ENV_SYSTEM = "THREATCODE_SYSTEM_HTTPS_PROXY"
const THREATCODE_HTTP_PROXY_ENV_SYSTEM = "THREATCODE_SYSTEM_HTTP_PROXY"
const THREATCODE_HTTP_NO_PROXY_ENV_SYSTEM = "THREATCODE_SYSTEM_NO_PROXY"
